![](https://github.com/simonscmap/pycmap/blob/master/docs/figures/CMAP.png?raw=true)

*Mohammad D. Ashkezari*

CBIOMES ML, APR 2026



<br/><br/><br/>

## Installation
pycmap can be installed using *pip*: 
<br />`pip install pycmap`

In order to use pycmap, you will need to obtain an API key from SimonsCMAP website:
<a href="https://simonscmap.com">https://simonscmap.com</a>.

### Note:
You may install pycmap on cloud-based jupyter notebooks (such as [Colab](https://colab.research.google.com/)) by running the following command in a code-block: 
<br />`!pip install pycmap`

## Installation
pycmap can be installed using *pip*: 
<br />`pip install pycmap`


### Note:
You may install pycmap on cloud-based jupyter notebooks (such as [Colab](https://colab.research.google.com/)) by running the following command in a code-block: 
<br />`!pip install pycmap`

In [17]:
# !pip install pycmap -q    #uncomment to install pycmap on Colab
import pycmap
pycmap.__version__

import warnings
warnings.filterwarnings("ignore")

## [*API( )*](https://cmap.readthedocs.io/en/latest/user_guide/API_ref/pycmap_api/pycmap_api.html#pycmapapi)
In order to use pycmap, you will need to obtain an API key from SimonsCMAP website:
<a href="https://simonscmap.com">https://simonscmap.com</a>.

To retrieve data, we need to create an instance of the system's API and pass the API key. It is not necessary to pass the API key every time you run pycmap, because the key will be stored locally.

In [18]:
# api = pycmap.API(token="YOUR_KEY")
api = pycmap.API()

## [*get_catalog()*](https://cmap.readthedocs.io/en/latest/user_guide/API_ref/pycmap_api/data_retrieval/pycmap_catalog.html#getcatalog)

Returns a dataframe containing the details of all variables at Simons CMAP database. 
<br />This method requires no input, and might take a minute to finish.

In [11]:
catalog_df = api.get_catalog()
catalog_df

,Variable,Table_Name,Long_Name,Unit,Make,Sensor,Process_Level,Study_Domain,Temporal_Resolution,Spatial_Resolution,...,Dataset_Name,Dataset_Short_Name,Data_Source,Distributor,Dataset_Description,Acknowledgement,Dataset_ID,ID,Unstructured_Dataset_Metadata,Unstructured_Variable_Metadata
0,cast,tblKM1513_HOE_legacy_2A_Dyhrman_Omics,Cast Number,NaN,Observation,Uncategorized,Reprocessed,Uncategorized,Irregular,Irregular,...,Diel Trichodesmium Metatranscriptomes,KM1513_HOE_legacy_2A_Dyhrman_Omics,"Sonya Dyhrman, LDEO/Columbia Univ.",Sonya Dyhrman - Columbia University,These datasets are from the SCOPE diel cruise ...,Sonya Dyhrman - Columbia University,570,11470,NaN,NaN
1,filter_max,tblKM1513_HOE_legacy_2A_Dyhrman_Omics,Filter Max,Âµm,Observation,Uncategorized,Reprocessed,Biology,Irregular,Irregular,...,Diel Trichodesmium Metatranscriptomes,KM1513_HOE_legacy_2A_Dyhrman_Omics,"Sonya Dyhrman, LDEO/Columbia Univ.",Sonya Dyhrman - Columbia University,These datasets are from the SCOPE diel cruise ...,Sonya Dyhrman - Columbia University,570,11471,NaN,NaN
2,filter_min,tblKM1513_HOE_legacy_2A_Dyhrman_Omics,Filter Min,Âµm,Observation,Uncategorized,Reprocessed,Biology,Irregular,Irregular,...,Diel Trichodesmium Metatranscriptomes,KM1513_HOE_legacy_2A_Dyhrman_Omics,"Sonya Dyhrman, LDEO/Columbia Univ.",Sonya Dyhrman - Columbia University,These datasets are from the SCOPE diel cruise ...,Sonya Dyhrman - Columbia University,570,11472,NaN,NaN
3,filter_type,tblKM1513_HOE_legacy_2A_Dyhrman_Omics,Filter Type,NaN,Observation,Uncategorized,Reprocessed,Biology,Irregular,Irregular,...,Diel Trichodesmium Metatranscriptomes,KM1513_HOE_legacy_2A_Dyhrman_Omics,"Sonya Dyhrman, LDEO/Columbia Univ.",Sonya Dyhrman - Columbia University,These datasets are from the SCOPE diel cruise ...,Sonya Dyhrman - Columbia University,570,11473,NaN,NaN
4,library_kit,tblKM1513_HOE_legacy_2A_Dyhrman_Omics,Sequencing Library Kit,NaN,Observation,Uncategorized,Reprocessed,Uncategorized,Irregular,Irregular,...,Diel Trichodesmium Metatranscriptomes,KM1513_HOE_legacy_2A_Dyhrman_Omics,"Sonya Dyhrman, LDEO/Columbia Univ.",Sonya Dyhrman - Columbia University,These datasets are from the SCOPE diel cruise ...,Sonya Dyhrman - Columbia University,570,11474,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12103,stress_curl_bias,tblWind_NRT_hourly,Scatterometer-Model Bias of Curl of Surface Wi...,N m-3,Observation,Satellite,Reprocessed,Physics,Hourly,1/8Â° X 1/8Â°,...,Global Ocean Hourly Sea Surface Wind and Stress,Wind_NRT_hourly,IFREMER CERSAT,https://marine.copernicus.eu/,"""The product contains hourly Level-4 sea surfa...",Dataset provided by E.U. Copernicus Marine Ser...,507,8896,NaN,NaN
12104,stress_curl_dv,tblWind_NRT_hourly,Difference of Scatterometer and Model Variance...,N2 m-6,Observation,Satellite,Reprocessed,Physics,Hourly,1/8Â° X 1/8Â°,...,Global Ocean Hourly Sea Surface Wind and Stress,Wind_NRT_hourly,IFREMER CERSAT,https://marine.copernicus.eu/,"""The product contains hourly Level-4 sea surfa...",Dataset provided by E.U. Copernicus Marine Ser...,507,8897,NaN,NaN
12105,air_density,tblWind_NRT_hourly,Air Density at 10 m,kg m-3,Observation,Satellite,Reprocessed,Physics,Hourly,1/8Â° X 1/8Â°,...,Global Ocean Hourly Sea Surface Wind and Stress,Wind_NRT_hourly,IFREMER CERSAT,https://marine.copernicus.eu/,"""The product contains hourly Level-4 sea surfa...",Dataset provided by E.U. Copernicus Marine Ser...,507,8898,NaN,NaN
12106,number_of_observations,tblWind_NRT_hourly,Number of Observations for Scatterometer-Model...,1,Observation,Satellite,Reprocessed,Physics,Hourly,1/8Â° X 1/8Â°,...,Global Ocean Hourly Sea Surface Wind and Stress,Wind_NRT_hourly,IFREMER CERSAT,https://marine.copernicus.eu/,"""The product contains hourly Level-4 sea surfa...",Dataset provided by E.U. Copernicus Marine Ser...,507,8899,NaN,NaN
12107,number_of_observations_divcurl,tblWind_NRT_hourly,Number of Observations for Scatterometer-Model...,1,Observation,Satellite,Reprocessed,Physics,Hourly,1/8Â° X 1/8Â°,...,Global Ocean Hourly Sea Surface Wind and Stress,Wind_NRT_hourly,IFREMER CERSAT,https://marine.copernicus.eu/,"""The product contains hourly Level-4 sea surfa...",Dataset provided by E.U. Copernicus Marine Ser...,507,8900,NaN,NaN

## [*search_catalog(keywords)*](https://cmap.readthedocs.io/en/latest/user_guide/API_ref/pycmap_api/data_retrieval/pycmap_search_catalog.html#searchcatalog)


Returns a dataframe containing a subset of Simons CMAP catalog of variables. 

All variables at Simons CMAP catalog are annotated with a collection of semantically related keywords. This method takes the passed keywords and returns all of the variables annotated with similar keywords. The passed keywords should be separated by blank space. The search result is not sensitive to the order of keywords and is not case sensitive. The passed keywords can provide any 'hint' associated with the target variables. Below are a few examples: 

* the exact variable name (e.g. NO3), or its linguistic term (Nitrate) 
* methodology (model, satellite ...), instrument (CTD, seaflow), or disciplines (physics, biology ...) 
* the cruise official name (e.g. KOK1606), or unofficial cruise name (Falkor) 
* the name of data producer (e.g Penny Chisholm) or institution name (MIT) 

<br />If you searched for a variable with semantically-related-keywords and did not get the correct results, please let us know. We can update the keywords at any point.

In [19]:
api.search_catalog("silicate in-situ")

,Variable,Table_Name,Long_Name,Unit,Make,Sensor,Process_Level,Study_Domain,Temporal_Resolution,Spatial_Resolution,...,Data_Source,Distributor,Dataset_Description,Acknowledgement,Dataset_ID,ID,Visualize,Keywords,Unstructured_Dataset_Metadata,Unstructured_Variable_Metadata
0,SiO4,tblHOE_legacy_2A,Silicate,umol/kg,Observation,Autoanalyzer,Reprocessed,Biogeochemistry,Irregular,Irregular,...,"Dave Karl, University of Hawaii, Manoa","University of Hawaii, Manoa",This dataset consists of samples taken at vari...,"C-MORE, Univeristy of Hawaii, Samuel Wilson",450,7688,1.0,"aloha, Autoanalyzer, BioGeoChemistry, cmore, C...",NaN,NaN
1,SiO4,tblHOE_Legacy_3,Silicate,umol/kg,Observation,Autoanalyzer,Reprocessed,Biogeochemistry,Irregular,Irregular,...,"Dave Karl, University of Hawaii, Manoa","University of Hawaii, Manoa",This dataset consists of samples taken at vari...,"C-MORE, University of Hawaii, Samuel Wilson",452,7728,1.0,"aloha, Autoanalyzer, BioGeoChemistry, cmore, C...",NaN,NaN
2,SiO4,tblHOE_Legacy_4,Silicate,umol/kg,Observation,Autoanalyzer,Reprocessed,Biogeochemistry,Irregular,Irregular,...,"Dave Karl, University of Hawaii, Manoa","University of Hawaii, Manoa",This dataset consists of samples taken at vari...,"C-MORE, SCOPE, University of Hawaii, Benedetto...",453,7746,1.0,"aloha, Autoanalyzer, BioGeoChemistry, cmore, C...",NaN,NaN
3,SiO4,tblHOT_LAVA,Silicate,umol/kg,Observation,Autoanalyzer,Reprocessed,Biogeochemistry,Irregular,Irregular,...,"Dave Karl, University of Hawaii, Manoa","University of Hawaii, Manoa",This dataset consists of samples taken at vari...,"SCOPE, Univeristy of Hawaii",454,7771,1.0,"Autoanalyzer, Core Data, cruise, CTD, Dave Kar...",NaN,NaN
4,SiO4,tblKM1906_Gradients3,Silicate,umol/kg,Observation,Autoanalyzer,Reprocessed,Biogeochemistry,Irregular,Irregular,...,"Angelique White, Scope-Gradients program, Univ...","University of Hawaii, Manoa",This dataset is from the Gradients 3 cruise (K...,"SCOPE-Gradients program, University of Hawaii,...",475,8093,1.0,"2019 SCOPE Gradients, Angelique White, Autoana...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,si_ma_clim,tblWOA_2018_1deg_Climatology,Seawater silicate concentration minus objectiv...,Âµmol/kg,Observation,In-Situ,Reprocessed,Physics+Chemistry,Monthly Climatology,1Â° X 1Â°,...,https://www.ncei.noaa.gov/data/oceans/ncei/woa/,https://www.ncei.noaa.gov/access/metadata/land...,âWorld Ocean Atlas 2018 (WOA18) is a set of ...,Data provided by: The National Oceanic and Atm...,459,7908,1.0,"atlas, chem, clim, climatology, cruise, in sit...",NaN,NaN
73,si_mn_clim,tblWOA_2018_1deg_Climatology,Average seawater silicate concentration,Âµmol/kg,Observation,In-Situ,Reprocessed,Physics+Chemistry,Monthly Climatology,1Â° X 1Â°,...,https://www.ncei.noaa.gov/data/oceans/ncei/woa/,https://www.ncei.noaa.gov/access/metadata/land...,âWorld Ocean Atlas 2018 (WOA18) is a set of ...,Data provided by: The National Oceanic and Atm...,459,7903,1.0,"atlas, Average seawater silicate concentration...",NaN,NaN
74,si_oa_clim,tblWOA_2018_1deg_Climatology,Mean seawater silicate concentration minus obj...,Âµmol/kg,Observation,In-Situ,Reprocessed,Physics+Chemistry,Monthly Climatology,1Â° X 1Â°,...,https://www.ncei.noaa.gov/data/oceans/ncei/woa/,https://www.ncei.noaa.gov/access/metadata/land...,âWorld Ocean Atlas 2018 (WOA18) is a set of ...,Data provided by: The National Oceanic and Atm...,459,7907,1.0,"atlas, chem, clim, climatology, cruise, in sit...",NaN,NaN
75,si_sd_clim,tblWOA_2018_1deg_Climatology,Standard deviation of mean seawater silicate c...,Âµmol/kg,Observation,In-Situ,Reprocessed,Physics+Chemistry,Monthly Climatology,1Â° X 1Â°,...,https://www.ncei.noaa.gov/data/oceans/ncei/woa/,https://www.ncei.noaa.gov/access/metadata/land...,âWorld Ocean Atlas 2018 (WOA18) is a set of ...,Data provided by: The National Oceanic and Atm...,459,7905,1.0,"atlas, chem, clim, climatology, cruise, in sit...",NaN,NaN
76,si_se_clim,tblWOA_2018_1deg_Climatology,Standard error of mean seawater silicate conce...,Âµmol/kg,Observation,In-Situ,Reprocessed,Physics+Chemistry,Monthly Climatology,1Â° X 1Â°,...,https://www.ncei.noaa.gov/data/oceans/ncei/woa/,https://www.ncei.noaa.gov/access/metadata/land...,âWorld Ocean Atlas 2018 (WOA18) is a set of ...,Data provided by: The National Oceanic and Atm...,459,7906,1.0,"atlas, chem, clim, climatology, cruise, in sit...",NaN,NaN

## [*get_dataset(tableName)*](https://cmap.readthedocs.io/en/latest/user_guide/API_ref/pycmap_api/data_retrieval/pycmap_retrieve_dataset.html#retrieve-dataset)

Returns the entire dataset. Note that this method does not return the dataset metadata. Use the Metadata method to get the dataset metadata.

> **Parameters:** 
>> **tableName: string**
>>  <br />Table name (each dataset is stored in a table). A full list of table names can be found in [catalog](https://simonscmap.com/catalog).
>> <br />


>**Returns:** 
>>  Pandas dataframe.

In [23]:
df = api.get_dataset("tblAMT13_Chisholm")
df.describe()

,lat,lon,depth,Pro_abundance,Pro_total_ecotype_abundance,Pro_eMED4_abundance,Pro_eMIT9312_abundance,Pro_eMIT9211_abundance,Pro_eNATL2A_abundance,Pro_eSS120_abundance,...,MLD_03Density_AMT13,MLD_125Density_AMT13,TotalDepth_AMT13,Pro_eMED4_abundance_quality,Pro_eMIT9312_abundance_quality,Pro_eMIT9211_abundance_quality,Pro_eNATL2A_abundance_quality,Pro_eSS120_abundance_quality,Pro_eMIT9313_abundance_quality,Pro_total_ecotype_abundance_quality
count,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000,...,275.000000,275.000000,239.000000,25.0,33.0,274.0,35.0,209.0,130.0,276.0
mean,-1.134912,-26.847060,83.840534,0.658341,49520.813571,11366.639753,35896.417580,1.066886,1931.274973,2.287345,...,48.860000,73.174545,4662.867782,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,31.048684,9.183746,59.851404,0.720206,70003.638523,26856.439718,67309.975069,0.656025,5650.170049,4.993088,...,47.070043,68.196638,1095.542560,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,-47.762000,-51.420000,0.000000,0.000000,5.154729,0.029686,0.122811,0.538449,0.213615,0.104029,...,6.500000,-9.000000,632.300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,-30.867000,-28.439000,36.804000,0.019733,592.685629,10.999977,7.762336,1.000000,3.555524,1.000000,...,15.500000,27.500000,4340.200000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.886000,-24.711000,68.066000,0.361200,7130.094520,387.997300,113.937745,1.000000,113.094280,1.000000,...,27.500000,38.500000,4799.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,27.221000,-20.943500,112.761500,1.227167,94360.038605,5548.510625,42199.008750,1.000000,906.206300,1.000000,...,66.500000,105.500000,5336.300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,47.983000,-11.539000,229.552000,3.069456,392711.217436,174335.400000,392677.450000,11.088730,46697.397500,49.444403,...,192.500000,261.500000,6143.300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## [*space_time(table, variable, dt1, dt2, lat1, lat2, lon1, lon2, depth1, depth2)*](https://cmap.readthedocs.io/en/latest/user_guide/API_ref/pycmap_api/data_retrieval/pycmap_subset_ST.html#subset-st)

Returns a subset of data according to the specified space-time constraints (dt1, dt2, lat1, lat2, lon1, lon2, depth1, depth2).
<br />The results are ordered by time, lat, lon, and depth (if exists), respectively.

> **Parameters:** 
>> **table: string**
>>  <br />Table name (each dataset is stored in a table). A full list of table names can be found in [catalog](https://simonscmap.com/catalog).
>> <br />
>> <br />**variable: string**
>>  <br />Variable short name which directly corresponds to a field name in the table. A subset of this variable is returned by this method according to the spatio-temporal cut parameters (below). Pass **'\*'** wild card to retrieve all fields in a table. A full list of variable short names can be found in [catalog](https://simonscmap.com/catalog).
>> <br />
>> <br />**dt1: string**
>>  <br />Start date or datetime. This parameter sets the lower bound of the temporal cut. <br />Example values: '2016-05-25' or '2017-12-10 17:25:00'
>> <br />
>> <br />**dt2: string**
>>  <br />End date or datetime. This parameter sets the upper bound of the temporal cut. 
>> <br />
>> <br />**lat1: float**
>>  <br />Start latitude [degree N]. This parameter sets the lower bound of the meridional cut. Note latitude ranges from -90&deg; to 90&deg;.
>> <br />
>> <br />**lat2: float**
>>  <br />End latitude [degree N]. This parameter sets the upper bound of the meridional cut. Note latitude ranges from -90&deg; to 90&deg;.
>> <br />
>> <br />**lon1: float**
>>  <br />Start longitude [degree E]. This parameter sets the lower bound of the zonal cut. Note longitue ranges from -180&deg; to 180&deg;.
>> <br />
>> <br />**lon2: float**
>>  <br />End longitude [degree E]. This parameter sets the upper bound of the zonal cut. Note longitue ranges from -180&deg; to 180&deg;.
>> <br />
>> <br />**depth1: float**
>>  <br />Start depth [m]. This parameter sets the lower bound of the vertical cut. Note depth is a positive number (it is 0 at surface and grows towards ocean floor).
>> <br />
>> <br />**depth2: float**
>>  <br />End depth [m]. This parameter sets the upper bound of the vertical cut. Note depth is a positive number (it is 0 at surface and grows towards ocean floor).


>**Returns:** 
>>  Pandas dataframe.

### Example:
This example retrieves a subset of in-situ salinity measurements by [Argo floats](https://simonscmap.com/catalog/datasets/ARGO_Core).

In [24]:
api.space_time(
              table="tblArgoCore_REP", 
              variable="PSAL", 
              dt1="2022-05-01", 
              dt2="2022-05-30", 
              lat1=28, 
              lat2=38, 
              lon1=-71, 
              lon2=-50, 
              depth1=0, 
              depth2=100
              )

                     time       lat        lon      depth       PSAL
0     2022-05-01T06:05:47  31.71048 -54.794090   0.397222  36.716000
1     2022-05-01T06:05:47  31.71048 -54.794090   1.032776  36.719002
2     2022-05-01T06:05:47  31.71048 -54.794090   1.986103  36.720001
3     2022-05-01T06:05:47  31.71048 -54.794090   2.979148  36.720001
4     2022-05-01T06:05:47  31.71048 -54.794090   4.051630  36.720001
...                   ...       ...        ...        ...        ...
6771  2022-05-29T17:43:00  35.85952 -65.754753  96.170573  36.568001
6772  2022-05-29T17:43:00  35.85952 -65.754753  97.063588  36.566002
6773  2022-05-29T17:43:00  35.85952 -65.754753  98.055820  36.563000
6774  2022-05-29T17:43:00  35.85952 -65.754753  99.048048  36.561001
6775  2022-05-29T17:43:00  35.85952 -65.754753  99.941043  36.561001

[6776 rows x 5 columns]

## *time_series(table, variable, dt1, dt2, lat1, lat2, lon1, lon2, depth1, depth2, interval=None)*

Returns a subset of data according to the specified space-time constraints (dt1, dt2, lat1, lat2, lon1, lon2, depth1, depth2). The returned data subset is aggregated by time: at each time interval the mean and standard deviation of the variable values within the space-time constraints are computed. The sequence of these values construct the timeseries. The timeseries data can be binned weekly, monthly, quarterly, or annually, if the **interval** parameter is set (this feature is not applicable to climatological datasets). The resulted timeseries is returned in form of a Pandas datframe ordered by time.

> **Parameters:** 
>> **table: string**
>>  <br />Table name (each dataset is stored in a table). A full list of table names can be found in catalog.
>> <br />
>> <br />**variable: string**
>>  <br />Variable short name which directly corresponds to a field name in the table. A subset of this variable is returned by this method according to the spatio-temporal cut parameters (below). A full list of variable short names can be found in catalog.
>> <br />
>> <br />**dt1: string**
>>  <br />Start date or datetime. This parameter sets the lower bound of the temporal cut. <br />Example values: '2016-05-25' or '2017-12-10 17:25:00'
>> <br />
>> <br />**dt2: string**
>>  <br />End date or datetime. This parameter sets the upper bound of the temporal cut. 
>> <br />
>> <br />**lat1: float**
>>  <br />Start latitude [degree N]. This parameter sets the lower bound of the meridional cut. Note latitude ranges from -90&deg; to 90&deg;.
>> <br />
>> <br />**lat2: float**
>>  <br />End latitude [degree N]. This parameter sets the upper bound of the meridional cut. Note latitude ranges from -90&deg; to 90&deg;.
>> <br />
>> <br />**lon1: float**
>>  <br />Start longitude [degree E]. This parameter sets the lower bound of the zonal cut. Note latitude ranges from -180&deg; to 180&deg;.
>> <br />
>> <br />**lon2: float**
>>  <br />End longitude [degree E]. This parameter sets the upper bound of the zonal cut. Note latitude ranges from -180&deg; to 180&deg;.
>> <br />
>> <br />**depth1: float**
>>  <br />Start depth [m]. This parameter sets the lower bound of the vertical cut. Note depth is a positive number (it is 0 at surface and grows towards ocean floor).
>> <br />
>> <br />**depth2: float**
>>  <br />End depth [m]. This parameter sets the upper bound of the vertical cut. Note depth is a positive number (it is 0 at surface and grows towards ocean floor).
>> <br />
>> <br />**interval: None or string, default: None**
>>  <br />The timeseries bin size. If None, the native dataset time resolution is used as the bin size. <br />Below is a list of interval values for other binning options:
* **'w'** or **'week'** for weekly timeseries.
* **'m'** or **'month'** for monthly timeseries.
* **'s'** or **'q'** for seasonal/quarterly timeseries.
* **'a'** or **'y'** for annual/yearly timeseries.

>**Returns:** 
>>  Pandas dataframe.

### Example

This example retrieves the timeseries of NO2 measurements conducted by [HOT team](http://hahana.soest.hawaii.edu/hot/hot-dogs/) at University of Hawaii, spanning from 1988 to 2016.

In [8]:
api.time_series(
               table='tblHOT_Bottle_ALOHA', 
               variable='no2', 
               dt1='1988-12-01', 
               dt2='2016-10-15', 
               lat1=22, 
               lat2=23, 
               lon1=-159, 
               lon2=-157, 
               depth1=0, 
               depth2=10
               )

                    time    lat  lon     depth  no2  no2_std
0    1988-12-02T00:00:00  22.75 -158  1.515419  NaN      NaN
1    1988-12-03T00:00:00  22.75 -158  2.603527  NaN      NaN
2    1989-01-08T00:00:00  22.75 -158  4.272957  NaN      NaN
3    1989-01-09T00:00:00  22.75 -158  5.723736  NaN      NaN
4    1989-01-10T00:00:00  22.75 -158  4.074218  NaN      NaN
..                   ...    ...  ...       ...  ...      ...
814  2016-07-13T00:00:00  22.75 -158  5.323439  NaN      NaN
815  2016-08-09T00:00:00  22.75 -158  5.515080  NaN      NaN
816  2016-08-10T00:00:00  22.75 -158  5.559243  NaN      NaN
817  2016-08-11T00:00:00  22.75 -158  5.323439  NaN      NaN
818  2016-10-15T00:00:00  22.75 -158  5.525017  NaN      NaN

[819 rows x 6 columns]

## Custom Colocalization:
<code>Sample(source, targets, replaceWithMonthlyClimatolog)<code/>

<br />Samples the target datasets using the time-location coordinates of the source dataset. The source dataset can be any dataframe with time and location (lat, lon, depth) columns, and therefore it doesn't necessarily need to be hosted in Simons CMAP database. For instance, you may load your own csv file and pass it as the source dataset to the `source` argument. The target datasets need to be in the Simons CMAP database and should be specified by a dictionary object as described below. The results strongly rely on the tolerance parameters (specified within the targets dictionary) because they set the matching boundaries between the source and target datasets.



> **Parameters:** 
>> **source: dataframe**
>>  <br />A dataframe containing the source datasets (must have time-location columns).
>> <br />
>> <br />**targets: dict**
>>  <br />A dcitionary containing the target table/variables and tolerance parameters. The keys must be table names and the sampling variables should be enumerated by the `variables` attribute. The items in `tolerances` list are: temporal tolerance [days], meridional tolerance [deg], 
>>    zonal tolerance [deg], and vertical tolerance [m], repectively.
>>    Below is an example for `targets` parameter:<br />
>>    <br />targets = {
>>    <br />        "tblSST_AVHRR_OI_NRT": {
>>    <br />                                "variables": ["sst"],
>>    <br />                                "tolerances": [1, 0.25, 0.25, 5]
>>    <br />                                },
>>    <br />        "tblPisces_NRT": {
>>    <br />                                "variables": ["NO3", "PO4", "Fe", "O2", "Si", "PP"],
>>    <br />                                "tolerances": [4, 0.5, 0.5, 5]
>>    <br />                               }
>>    <br />        }    
>> <br />
Please explore the catalog to find more target datasets. 
<br /><br />
>> <br />**replaceWithMonthlyClimatolog: boolean**
>>  <br />If `True`, monthly climatology of the target variables is sampled when the target dataset's temporal range does not cover the source data. If `False`, only contemporaneous target data are sampled. 
>> <br />

>**Returns:** 
>>  Pandas dataframe containing the original source dataframe joined by the target dataset variables.

In [13]:
targets = {
            "tblSST_AVHRR_OI_NRT": {
                                    "variables": ["sst"],
                                    "tolerances": [0, 0.25, 0.25, 0]
                                    },
    
            }


pycmap.Sample(
              source=api.get_dataset("tblAMT13_Chisholm"), 
              targets=targets, 
              replaceWithMonthlyClimatolog=True
             )

Gathering metadata ....
Sampling starts
Sampling finished

,time,lat,lon,depth,Pro_abundance,Pro_total_ecotype_abundance,Pro_eMED4_abundance,Pro_eMIT9312_abundance,Pro_eMIT9211_abundance,Pro_eNATL2A_abundance,...,MLD_125Density_AMT13,TotalDepth_AMT13,Pro_eMED4_abundance_quality,Pro_eMIT9312_abundance_quality,Pro_eMIT9211_abundance_quality,Pro_eNATL2A_abundance_quality,Pro_eSS120_abundance_quality,Pro_eMIT9313_abundance_quality,Pro_total_ecotype_abundance_quality,CMAP_sst_tblSST_AVHRR_OI_NRT
0,2003-09-14T09:55:00,47.983,-11.539,9.280,0.920600,96901.054453,95878.590000,96.139927,1.000000,923.324525,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,18.225000
1,2003-09-14T09:55:00,47.983,-11.539,43.017,0.269000,21001.014360,19852.152500,24.226982,1.000000,1121.921075,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,0.0,18.225000
2,2003-09-14T09:55:00,47.983,-11.539,53.629,0.123600,4502.290607,3847.636500,6.132032,1.000000,645.522075,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,18.225000
3,2003-09-14T09:55:00,47.983,-11.539,62.327,0.095467,2468.064461,2120.974000,4.158968,3.010477,338.685800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.225000
4,2003-09-14T09:55:00,47.983,-11.539,78.587,0.057667,2315.212687,1420.990750,2.133862,1.000000,889.088075,...,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,0.0,18.225000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,2003-10-12T12:43:59,-47.762,-51.420,62.744,0.001800,5.623099,1.261979,0.821804,1.000000,0.391510,...,97.5,6143.3,NaN,NaN,0.0,NaN,0.0,NaN,0.0,8.584985
279,2003-10-12T12:43:59,-47.762,-51.420,83.045,0.001867,5.154729,0.697516,0.457213,1.000000,1.000000,...,97.5,6143.3,NaN,NaN,0.0,0.0,0.0,0.0,0.0,8.584985
280,2003-10-12T12:43:59,-47.762,-51.420,103.250,0.001267,14.260102,7.436363,1.007110,1.000000,0.759817,...,97.5,6143.3,NaN,NaN,0.0,NaN,0.0,NaN,0.0,8.584985
281,2003-10-12T12:43:59,-47.762,-51.420,163.682,0.000533,5.353990,0.353990,1.000000,1.000000,1.000000,...,97.5,6143.3,NaN,0.0,0.0,0.0,0.0,0.0,0.0,8.584985
282,2003-10-12T12:43:59,-47.762,-51.420,204.208,0.000333,8.493098,2.347005,0.758111,1.000000,2.554832,...,97.5,6143.3,NaN,NaN,0.0,NaN,NaN,NaN,0.0,8.584985

## [*query(sql)*](https://cmap.readthedocs.io/en/latest/user_guide/API_ref/pycmap_api/data_retrieval/pycmap_query.html#query)
<br />This method takes a custom SQL (read) query statement and returns the results in form of a Pandas dataframe. 

Please keep in mind that some of the datasets are massive in size, avoid queries without WHERE clause (`SELECT * FROM TABLENAME`). Always add some constraints on time, lat, lon, and depth fields (see the basic examples below).

### Example:
A sample query returning the timeseries of sea surface temperature (sst).

In [30]:
api.query(
         '''
         SELECT [time], AVG(lat) AS lat, AVG(lon) AS lon, AVG(sst) AS sst FROM tblsst_AVHRR_OI_NRT
         WHERE
         [time] BETWEEN '2016-06-01' AND '2016-10-01' AND
         lat BETWEEN 23 AND 24 AND
         lon BETWEEN -160 AND -158
         GROUP BY [time]
         ORDER BY [time]
         '''
         )

                    time   lat  lon        sst
0    2016-06-01T00:00:00  23.5 -159  25.316556
1    2016-06-02T00:00:00  23.5 -159  25.277493
2    2016-06-03T00:00:00  23.5 -159  25.245618
3    2016-06-04T00:00:00  23.5 -159  25.157493
4    2016-06-05T00:00:00  23.5 -159  25.301243
..                   ...   ...  ...        ...
118  2016-09-27T00:00:00  23.5 -159  26.449993
119  2016-09-28T00:00:00  23.5 -159  26.394056
120  2016-09-29T00:00:00  23.5 -159  26.378118
121  2016-09-30T00:00:00  23.5 -159  26.425618
122  2016-10-01T00:00:00  23.5 -159  26.346868

[123 rows x 4 columns]